2021-06-08 15:34:11 UTC Imported #12594712 0x972d…1883 (153 txs, 14.97 Mgas, 11454 ms, 46.65 KiB)
2021-06-08 15:34:17 UTC  37/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:34:47 UTC  37/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:34:47 UTC Imported #12594713 0x9f2a…c786 (210 txs, 14.97 Mgas, 4288 ms, 76.55 KiB)
2021-06-08 15:35:06 UTC Imported #12594715 0x16c0…b1da (205 txs, 14.98 Mgas, 6054 ms, 65.36 KiB)
2021-06-08 15:35:18 UTC  37/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:35:49 UTC  40/50 peers      3 MiB chain  198 KiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:36:03 UTC Imported #12594718 0x1b1d…878d (215 txs, 14.98 Mgas, 5874 ms, 62.75 KiB)
2021-06-08 15:36:10 UTC Imported #12594719 0x6bf9…5ede (197 txs, 14.98 Mgas, 7086 ms, 60.76 KiB)
2021-06-08 15:36:22 UTC  39/50 peers      4 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:36:36 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::update_stream
   8: mio::deprecated::event_loop::EventLoop<H>::run
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  12: start_thread
  13: __clone


Thread '<unnamed>' panicked at 'Error reregistering UDP socket: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', crates/net/network-devp2p/src/host.rs:1425

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-06-08 15:36:36 UTC Finishing work, please wait...
Error: 1