2021-06-08 15:00:31 UTC Imported #12594561 0xd09d…46d4 (187 txs, 15.00 Mgas, 7844 ms, 56.93 KiB)
2021-06-08 15:00:52 UTC Imported #12594562 0x189a…81e4 (213 txs, 14.99 Mgas, 8029 ms, 58.19 KiB)
2021-06-08 15:01:03 UTC  36/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:01:08 UTC Imported #12594563 0xd2e0…e000 (155 txs, 14.98 Mgas, 8033 ms, 54.41 KiB)
2021-06-08 15:01:35 UTC  36/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:01:43 UTC Imported #12594564 0x3bad…5827 (232 txs, 14.98 Mgas, 7407 ms, 65.54 KiB)
2021-06-08 15:02:07 UTC  36/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:02:12 UTC Imported #12594565 0x28da…addb (187 txs, 14.97 Mgas, 5833 ms, 51.36 KiB)
2021-06-08 15:02:41 UTC  37/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:02:46 UTC Imported #12594569 0x10c9…e4d5 (195 txs, 14.98 Mgas, 6508 ms, 65.35 KiB)
2021-06-08 15:03:06 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::update_stream
   8: mio::deprecated::event_loop::EventLoop<H>::run
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  12: start_thread
  13: __clone


Thread '<unnamed>' panicked at 'Error reregistering UDP socket: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/net/network-devp2p/src/host.rs:1425

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-06-08 15:03:06 UTC Finishing work, please wait...
2021-06-08 15:03:08 UTC Imported #12594570 0xcfdf…ec25 (234 txs, 14.97 Mgas, 5847 ms, 55.79 KiB)
2021-06-08 15:03:09 UTC Error on IO service shutdown: NotifyError::Closed(..)
Error: 1