2021-05-09 11:22:51 UTC Syncing #12399717 0x2514…279e     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  173 Qed Ancient:#12135598 LI:#12399885   32/50 peers      1 MiB chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:22:59 UTC Syncing #12399719 0x1b2e…a988     0.29 blk/s   75.9 tx/s    4.3 Mgas/s      0+  172 Qed Ancient:#12135666 LI:#12399885   32/50 peers      3 MiB chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:23:10 UTC Syncing #12399720 0x1665…3f4f     0.09 blk/s   23.2 tx/s    1.4 Mgas/s      0+  171 Qed Ancient:#12135914 LI:#12399885   32/50 peers      5 MiB chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:23:40 UTC Syncing #12399720 0x1665…3f4f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  174 Qed Ancient:#12136928 LI:#12399888   27/50 peers      2 MiB chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:23:53 UTC Syncing #12399721 0x4d1e…676b     0.08 blk/s   19.2 tx/s    1.2 Mgas/s      0+  174 Qed Ancient:#12137745 LI:#12399889   25/25 peers   728 bytes chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:23:53 UTC Syncing #12399721 0x4d1e…676b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  174 Qed Ancient:#12137745 LI:#12399889   25/25 peers   728 bytes chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:23:53 UTC Syncing #12399721 0x4d1e…676b     0.08 blk/s   19.2 tx/s    1.2 Mgas/s      0+  174 Qed Ancient:#12137745 LI:#12399889   25/25 peers     18 MiB chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:23:53 UTC Syncing #12399721 0x4d1e…676b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  174 Qed Ancient:#12137745 LI:#12399889   25/25 peers   728 bytes chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:23:56 UTC Syncing #12399721 0x4d1e…676b     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+  174 Qed Ancient:#12137745 LI:#12399890   25/25 peers     74 KiB chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:24:01 UTC Syncing #12399722 0x5624…e2a8     0.20 blk/s   51.6 tx/s    3.0 Mgas/s      0+  173 Qed Ancient:#12137745 LI:#12399890   26/50 peers    109 KiB chain   40 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-05-09 11:25:41 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: ethcore::client::client::IoChannelQueue::queue::{{closure}}
   8: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
   9: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  10: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  14: start_thread
  15: __clone


Thread 'Worker Client3' panicked at 'DB flush failed.: Custom { kind: Other, error: "IO error: While open a file for appending: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1100289.log: No such file or directory" }', crates/ethcore/src/client/client.rs:573

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-05-09 11:25:41 UTC Finishing work, please wait...
2021-05-09 11:25:41 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: ethcore::client::client::IoChannelQueue::queue::{{closure}}
   8: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
   9: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  10: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  14: start_thread
  15: __clone


Thread 'Worker Client1' panicked at 'DB flush failed.: Custom { kind: Other, error: "IO error: While open a file for appending: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1100289.log: No such file or directory" }', crates/ethcore/src/client/client.rs:573

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-05-09 11:25:41 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: ethcore::client::client::IoChannelQueue::queue::{{closure}}
   8: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
   9: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  10: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  14: start_thread
  15: __clone


Thread 'Worker Client2' panicked at 'DB flush failed.: Custom { kind: Other, error: "IO error: While open a file for appending: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1100289.log: No such file or directory" }', crates/ethcore/src/client/client.rs:573

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-05-09 11:25:41 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: ethcore::client::client::IoChannelQueue::queue::{{closure}}
   8: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
   9: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  10: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  14: start_thread
  15: __clone


Thread 'Worker Client0' panicked at 'DB flush failed.: Custom { kind: Other, error: "IO error: While open a file for appending: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1100289.log: No such file or directory" }', crates/ethcore/src/client/client.rs:573

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


Error: 1