2021-06-08 15:21:36 UTC  33/50 peers      2 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:21:41 UTC Imported #12594655 0x6d8e…d654 (179 txs, 14.89 Mgas, 11308 ms, 58.90 KiB)
2021-06-08 15:22:12 UTC  33/50 peers      2 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:22:22 UTC Imported #12594656 0x2975…5318 (157 txs, 14.86 Mgas, 9087 ms, 60.81 KiB)
2021-06-08 15:22:44 UTC  33/50 peers      2 MiB chain  420 KiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:23:14 UTC  32/50 peers      2 MiB chain  570 KiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:23:44 UTC  33/50 peers      2 MiB chain  882 KiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:24:15 UTC  32/50 peers      2 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:24:17 UTC Imported #12594669 0x50f6…70fe (201 txs, 14.92 Mgas, 5872 ms, 55.50 KiB)
2021-06-08 15:24:49 UTC  33/50 peers      3 MiB chain  402 KiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:25:25 UTC  33/50 peers      3 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2021-06-08 15:25:29 UTC Imported #12594677 0xdb59…918d (195 txs, 14.96 Mgas, 6530 ms, 57.33 KiB)
2021-06-08 15:25:47 UTC Panic occured, see stderr for details


====================

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/option.rs:1300
   7: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::update_stream
   8: mio::deprecated::event_loop::EventLoop<H>::run
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
  12: start_thread
  13: __clone


Thread '<unnamed>' panicked at 'Error reregistering UDP socket: Os { code: 28, kind: Other, message: "No space left on device" }', crates/net/network-devp2p/src/host.rs:1425

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-06-08 15:25:47 UTC Finishing work, please wait...
2021-06-08 15:25:47 UTC Error on IO service shutdown: NotifyError::Closed(..)
Error: 1
pthread lock: Invalid argument